2024-10-25 14:17:54,466 # WARNING # Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Kolchanov\PycharmProjects\test2Project\module 12\12_4.py", line 20, in test_new_run
    start = Runner(['Karl'])
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Kolchanov\PycharmProjects\test2Project\module 12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-10-25 14:17:54,468 # WARNING # Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Kolchanov\PycharmProjects\test2Project\module 12\12_4.py", line 8, in test_new_walk
    start = Runner('Bob', speed=-5)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kolchanov\PycharmProjects\test2Project\module 12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
